#!/bin/sh


#
#  Apache + PHP
#
docker build -t skxskx/apache2-php5 apache2-php5/

#
#  Beanstalkd
#
docker build -t skxskx/beanstalkd beanstalkd/

#
#  Memcached
#
docker build -t skxskx/memcached  memcached/

#
#  Redis
#
docker build -t skxskx/redis redis/

#
#  sshd
#
docker build -t skxskx/sshd sshd/
